spring.application.name=demo
server.port=${SERVER_PORT:5000}

spring.datasource.url=${DB_URL:jdbc:mysql://mysql-dbas-jkt-001.sumobase.my.id:63306/db851d5e985f0e9c57?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Jakarta}
spring.datasource.username=${DB_USERNAME:uxr61iBxxbcJ8xHG6}
spring.datasource.password=${DB_PASSWORD:d5ba5229e2375256e7a2b680}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

logging.level.com.DigitalVillageHub.demo=DEBUG

# HikariCP Connection Pool Optimization
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.connection-timeout=20000
